name: Keep Render Alive

# on:
#   schedule:
#     - cron: "*/5 7-21 * * *"
#   workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping DEV API
        run: |
          curl -s https://dev-docnow-api.onrender.com/health || echo "Dev ping failed"
      
      - name: Ping PROD API
        run: |
          curl -s https://prod-docnow-api.onrender.com/health || echo "Prod ping failed"
